### ISSUE TITLE
e2e tests: Type system i18n characters test fails

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#124]
```
 FAIL  src/e2etests/typeSystem.test.js (10.734s)
  ● Console

    console.error src/e2etests/puppetHelpers.js:51
      Timeout waiting for element ".modal.show input#typeName.form-control". See screenshot at screenshot_2019-09-26T21:15:07.190Z.png

  ● Should accept i18n characters in type names

    Timeout 5000ms exceeded

      40 |         );
      41 |     }
    > 42 |     throw new Error(`Timeout ${timeout}ms exceeded`);
         |           ^
      43 | };
      44 | 
      45 | export const waitForElement = async (page, query, { timeout = 2000 } = {}) => {

      at _callee$ (src/e2etests/puppetHelpers.js:42:11)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (src/e2etests/puppetHelpers.js:43:103)
      at _next (src/e2etests/puppetHelpers.js:45:194)

```

**Comment by paulftw** [comment]
e4d745c5b01 will probably fix this

**Comment by paulftw** [comment]
Ratel build is green now. Closing.
https://teamcity.dgraph.io/viewLog.html?buildId=27035&buildTypeId=Ratel_Build
