### ISSUE TITLE
Failed at the ratel-client@0.0.1 start script.

### ISSUE THREAD

**Issue by chandra155** [dgraph-io/ratel#92]
After installing npm dependencies, when trying to start project by npm start getting error.

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at getClientEnvironment (C:\Users\Z0042HDB\Downloads\ratel-master\ratel-master\client\config\env.js:83:41)
    at Object.<anonymous> (C:\Users\Z0042HDB\Downloads\ratel-master\ratel-master\client\config\webpack.config.dev.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ratel-client@0.0.1 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ratel-client@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please help

**Comment by campoy** [comment]
Hey @paulftw, could you have a look at this bug and make sure you add some documentation on how to correctly run ratel from source code?

Thanks!

**Comment by paulftw** [comment]
@chandra155 what is the output of `git rev-parse --short HEAD` when you run it in the `ratel/client` folder?
Seems like your source folder is not in a git repository. Did you download a zip archive or something?

**Comment by chandra155** [comment]
@paulftw hi Paul ,  i download the zip archive.

**Comment by paulftw** [comment]
Fixed in https://github.com/dgraph-io/ratel/commit/6c9b5bf1406e62fe640b7e56fa78140c81a2b778

**Comment by paulftw** [comment]
Feel free to re-open this bug if the issue persists with the patch above
